apps/base/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('base',
    url(r'^image-preview/(?P<app_label>\w+)/(?P<model>\w+)/(?P<id>\d+)/(?P<size>(\d+|\d+x\d+))/$', 'views.image_preview', name="image_preview"),
    url(r'^clear-cache/$', 'views.clear_cache', name='clear_cache'),
)

apps/make_payments/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('make_payments.views',                  
    url(r'^$', 'add', name="make_payment.add"),
    url(r'^conf/(?P<id>\d+)/$', 'add_confirm', name="make_payment.add_confirm"), 
    url(r'^(?P<id>\d+)/$', 'view', name="make_payment.view"), 
)

apps/memberships/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns("memberships.views",


    # memberships
    url(r"^memberships/(?P<id>\d+)/$", "membership_details", name="membership.details"),

    # entries
    url(r"^entries/$", "application_entries", name="membership.application_entries"),
    url(r"^entries/(?P<id>\d+)/$", "application_entries", name="membership.application_entries"),
    url(r"^entries/search/$", "application_entries_search", name="membership.application_entries_search"),

    # application
    url(r"^confirmation/(?P<hash>[\w]+)/$", "application_confirmation", name="membership.application_confirmation"),
    url(r"^(?P<slug>[\w\-]+)/(?P<cmb_id>\d+)?/?$", "application_details", name="membership.application_details"),
    url(r"^(?P<slug>[\w\-]+)/corp-pre/(?P<cmb_id>\d+)?/?$", "application_details_corp_pre", name="membership.application_details_corp_pre"),
    
)

urls.py
from os.path import join
from django.conf.urls.defaults import *
from django.conf import settings
from django.views.generic.simple import direct_to_template, redirect_to
from django.conf import settings

# Django admin
from django.contrib import admin
admin.autodiscover()

# App Registry
import registry
registry.autodiscover()

urlpatterns = patterns('',
    url(r'^$', direct_to_template, {"template": "homepage.html", }, name="home"),

    #Reports:
    (r'^reports/', include('reports.urls')),
    url(r'^event-logs/reports/summary/$', 'event_logs.views.event_summary_report', name='reports-events-summary'),
    url(r'^event-logs/reports/summary/([^/]+)/$', 'event_logs.views.event_source_summary_report', name='reports-events-source'),
    url(r'^users/reports/users-activity-top10/$', 'profiles.views.user_activity_report', name='reports-user-activity'),
    url(r'^users/reports/active-logins/$', 'profiles.views.user_access_report', name='reports-user-access'),
    url(r'^users/reports/admin/$', 'profiles.views.admin_users_report', name='reports-admin-users'),
    url(r'^users/reports/users-added/$', 'user_groups.views.users_added_report', {'kind': 'added'}, name='reports-user-added'),
    url(r'^users/reports/contacts-referral/$', 'user_groups.views.users_added_report', {'kind': 'referral'}, name='reports-contacts-referral'),
    url(r'^articles/reports/rank/$', 'articles.views.articles_report', name='reports-articles'),

    (r'^notifications/', include('notification.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^base/', include('base.urls')),
    (r'^avatar/', include('avatar.urls')),
    (r'^dashboard/', include('dashboard.urls')),
    (r'^categories/', include('categories.urls')),
    (r'^articles/', include('articles.urls')),
    (r'^entities/', include('entities.urls')),
    (r'^locations/', include('locations.urls')),
    (r'^pages/', include('pages.urls')),
    (r'^users/', include('profiles.urls')),
    (r'^photos/', include('photos.urls')),
    (r'^forms/', include('forms_builder.forms.urls')),
    (r'^events/', include('events.urls')),
    (r'^profiles/', include('profiles.urls')),
    (r'^groups/', include('user_groups.urls')),
    (r'^stories/', include('stories.urls')),
    (r'^invoices/', include('invoices.urls')),
    (r'^py/', include('make_payments.urls')),
    (r'^payments/', include('payments.urls')),
    (r'^accountings/', include('accountings.urls')),
    (r'^emails/', include('emails.urls')),
    (r'^newsletters/', include('newsletters.urls')),
    (r'^actions/', include('actions.urls')),
    (r'^rss/', include('rss.urls')),
    (r'^imports/', include('imports.urls')),
    #(r'^donations/', include('donations.urls')),
    (r'^news/', include('news.urls')),
    (r'^settings/', include('site_settings.urls')),
    (r'^files/', include('files.urls')),
    (r'^contacts/', include('contacts.urls')),
    (r'^accounts/', include('accounts.urls')),
    (r'^search/', include('search.urls')),
    (r'^event-logs/', include('event_logs.urls')),
    (r'^contributions/', include('contributions.urls')),
    (r'^theme-editor/', include('theme_editor.urls')),
    (r'^jobs/', include('jobs.urls')),
    (r'^directories/', include('directories.urls')),
    (r'^contact/', include('form_builder.urls')),
    (r'^sitemap.xml', include('sitemaps.urls')),
    (r'^help-files/', include('help_files.urls')),
    # third party (inside environment)
    (r'^tinymce/', include('tinymce.urls')),
    (r'^captcha/', include('captcha.urls')),
    (r'^redirects/', include('redirects.urls')),
    (r'^resumes/', include('resumes.urls')),
    (r'^mobile/', include('mobile.urls')),

    url(r'^sitemap/$', direct_to_template, {"template": "site_map.html", }, name="site_map"),
    url(r'^robots.txt', direct_to_template, {"template": "robots.txt", }, name="robots"),

    # legacy redirects
    url(r'^login/$', redirect_to, {'url': '/accounts/login/'}),
    
    # other t4 to t5 legacy redirects
    url(r'^en/', include('legacy.urls')),
)

handler500 = 'base.views.custom_error'

# serve static files
if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^site_media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': join(settings.PROJECT_ROOT, 'site_media')}),

        (r'^themes/%s/(?P<path>.*)$' % settings.SITE_THEME,
            'django.views.static.serve',
            {'document_root': settings.THEME_ROOT}),

        (r'^plugin-media/(?P<plugin>[^/]+)/(?P<path>.*)$',
            'base.views.plugin_static_serve'),
    )

# template tag testing environment
if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^tag-test/$', direct_to_template, {"template": "tag_test.html", }, name="tag_test"),
    )

# Local url patterns for development
try:
    from local_urls import extra_patterns
    urlpatterns += extra_patterns
except ImportError:
    pass

#PLUGINS:
import pluginmanager
urlpatterns += pluginmanager.get_url_patterns()

# tack on the pages pattern at the very end so let custom and software patterns
# happen first
pattern_pages = patterns('',
    # page view
    url(r'^(?P<slug>[\w\-\/]+)/$', 'pages.views.index', name="page"),  
)
urlpatterns += pattern_pages

apps/make_payments/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

from perms.utils import is_admin

class MakePayment(models.Model):
    guid = models.CharField(max_length=50)
    user = models.ForeignKey(User, null=True)
    first_name = models.CharField(max_length=100, null=True)
    last_name = models.CharField(max_length=100, null=True)
    company = models.CharField(max_length=50, default='', blank=True, null=True)
    address = models.CharField(max_length=100, default='', blank=True, null=True)
    address2 = models.CharField(_('address line 2'), max_length=100, default='', blank=True, null=True)
    city = models.CharField(max_length=50, default='', blank=True, null=True)
    state = models.CharField(max_length=50, default='', blank=True, null=True)
    zip_code = models.CharField(max_length=50, default='', blank=True, null=True)
    country = models.CharField(max_length=50, default='', blank=True, null=True)
    email = models.CharField(max_length=50, default='',  null=True)
    phone = models.CharField(max_length=50, default='', blank=True, null=True)
    referral_source = models.CharField(_('referred by'), max_length=200, default='', blank=True, null=True)
    comments = models.TextField(blank=True, null=True)
    payment_amount = models.DecimalField(max_digits=10, decimal_places=2)
    payment_count = models.IntegerField(blank=True, null=True)
    payment_method = models.CharField(max_length=50, default='cc')
    invoice_id = models.IntegerField(blank=True, null=True)
    create_dt = models.DateTimeField(auto_now_add=True)
    creator = models.ForeignKey(User, null=True,  related_name="make_payment_creator")
    creator_username = models.CharField(max_length=50, null=True)
    owner = models.ForeignKey(User, null=True, related_name="make_payment_owner")
    owner_username = models.CharField(max_length=50, null=True)
    status_detail = models.CharField(max_length=50, default='estimate')
    status = models.BooleanField(default=True)

    
    class Meta:
        verbose_name = _("General Payment")
        verbose_name_plural = _("General Payments")
    
    def save(self, user=None):
        if not self.id:
            self.guid = str(uuid.uuid1())
            if user and user.id:
                self.creator=user
                self.creator_username=user.username
        if user and user.id:
            self.owner=user
            self.owner_username=user.username
            
        super(self.__class__, self).save()
        
    def allow_view_by(self, user2_compare):
        boo = False
        if is_admin(user2_compare):
            boo = True
        else: 
            if user2_compare and user2_compare.id > 0:
                if self.creator == user2_compare or self.owner == user2_compare:
                    if self.status == 1:
                        boo = True
            
        return boo
    
    # Called by payments_pop_by_invoice_user in Payment model.
    def get_payment_description(self, inv):
        """
        The description will be sent to payment gateway and displayed on invoice.
        If not supplied, the default description will be generated.
        """
        if self.comments:
            return 'Tendenci Invoice %d (Payment %d) %s' % (
                inv.id,
                inv.object_id,
                self.comments,
            )
        return
    
    def make_acct_entries(self, user, inv, amount, **kwargs):
        """
        Make the accounting entries for the general sale
        """
        from accountings.models import Acct, AcctEntry, AcctTran
        from accountings.utils import make_acct_entries_initial, make_acct_entries_closing
        
        ae = AcctEntry.objects.create_acct_entry(user, 'invoice', inv.id)
        if not inv.is_tendered:
            make_acct_entries_initial(user, ae, amount)
        else:
            # payment has now been received
            make_acct_entries_closing(user, ae, amount)
            
            # #CREDIT makepayment SALES
            acct_number = self.get_acct_number()
            acct = Acct.objects.get(account_number=acct_number)
            AcctTran.objects.create_acct_tran(user, ae, acct, amount*(-1)) 
            
    def get_acct_number(self, discount=False):
        if discount:
            return 466700
        else:
            return 406700

        
    

apps/base/forms.py
from re import compile
from django.core.validators import RegexValidator
from django.forms.fields import CharField
from django.utils.translation import ugettext_lazy as _

slug_re = compile(r'^[-\w\/]+$')
validate_slug = RegexValidator(slug_re, _(u"Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens."), 'invalid')

class SlugField(CharField):
    """
        New form slug field that validates with front slashes
        Straight copy from django with modifications
    """
    default_error_messages = {
        'invalid': _(u"Enter a valid 'slug' consisting of letters, numbers,"
                     u" underscores (_), front-slashes (/) or hyphens."),
    }
    default_validators = [validate_slug]
    
    def __init__(self, help_text=None, *args, **kwargs):
        super(SlugField, self).__init__(*args, **kwargs)
        
    def clean(self, value):
        value = self.to_python(value)     
        value = value.replace('//','')
        value = value.strip('/')

        self.validate(value)
        self.run_validators(value)
        
        return value
        

apps/make_payments/forms.py
from django import forms
from django.contrib.auth.models import User
from make_payments.models import MakePayment

class MakePaymentForm(forms.ModelForm):
    # get the payment_method choices from settings

    # TODO: Make check-paid an admin only option
    #payment_method = forms.CharField(widget=forms.RadioSelect(choices=(('check-paid', 'Paid by Check'),
    #                                                          ('cc', 'Make Online Payment'),)), initial='cc', )
    payment_method = forms.CharField(widget=forms.RadioSelect(choices=(('cc', 'Make Online Payment'),)), initial='cc',)
    company = forms.CharField(max_length=50, required=False, widget=forms.TextInput(attrs={'size':'30'}))
    address = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'size':'35'}))
    state = forms.CharField(max_length=50, required=False,  widget=forms.TextInput(attrs={'size':'5'}))
    zip_code = forms.CharField(max_length=20, required=False, widget=forms.TextInput(attrs={'size':'10'}))
    referral_source = forms.CharField(max_length=200, required=False, widget=forms.TextInput(attrs={'size':'40'}))
    email = forms.EmailField(help_text='A valid e-mail address, please.')
    email_receipt = forms.BooleanField(initial=True)
    
    class Meta:
        model = MakePayment
        fields = ('payment_amount',
                  'payment_method',
                  'first_name',
                  'last_name',
                  'company',
                  'address',
                  'address2',
                  'city',
                  'state',
                  'zip_code',
                  'country',
                  'phone',
                  'email',
                  'email_receipt',
                  'referral_source',
                  'comments',
                  )
        
    def __init__(self, user, *args, **kwargs):
        super(MakePaymentForm, self).__init__(*args, **kwargs)
        # populate the user fields
        if user and user.id:
            self.fields['first_name'].initial = user.first_name
            self.fields['last_name'].initial = user.last_name
            self.fields['email'].initial = user.email
            try:
                profile = user.get_profile()
                if profile:
                    self.fields['company'].initial = profile.company
                    self.fields['address'].initial = profile.address
                    self.fields['address2'].initial = profile.address2
                    self.fields['city'].initial = profile.city
                    self.fields['state'].initial = profile.state
                    self.fields['zip_code'].initial = profile.zipcode
                    self.fields['country'].initial = profile.country
                    self.fields['phone'].initial = profile.phone
            except:
                pass
        

templates/make_payments/add.html
{% extends "make_payments/base.html" %}
{% load i18n %}

{% block title %}Make a Payment{% endblock %}

{% block extra_head %}
{{ block.super }}
<link rel="stylesheet" href="/site_media/static/css/make_payments.css">
<style>
	
	.errorlist{
		color: red;
	}
	.payment-method-list{
		float: left;
	}
	.payment-method-list ul{
		margin-left: 0;
		padding-left: 0;
	}
	.payment-method-list ul li{
		list-style: none;
	}
	.field-wrapper span{
		color: #8A1F11;
		font-size: 0.8em;
	}
	
</style>
{% endblock %}

{% block body %}
<div class="t">

<h1>Make a Payment</h1>

<form method="post" action=".">
<div class="field-wrapper required">
	{% if form.payment_amount.errors %}
		{{ form.payment_amount.errors }}
	{% endif %}
	<label for="id_payment_amount" class="field-label">{% trans 'Payment Amount'%} ({{currency_symbol}}):</label>
	{{ form.payment_amount }}
</div>
<div class="clear-left"></div>

<div class="field-wrapper">
	{% if form.payment_method.errors %}
		{{ form.payment_method.errors }}
	{% endif %}
	<label for="id_payment_method" class="field-label">{% trans 'Payment Method:'%}</label>
	<div class="payment-method-list">{{ form.payment_method }}</div>
</div>
<div class="clear-left"></div>

<div class="field-wrapper required">
	{% if form.first_name.errors %}
		{{ form.first_name.errors }}
	{% endif %}
	<label for="id_first_name" class="field-label">{% trans 'First Name:'%}</label>
	{{ form.first_name }} 
</div>
<div class="clear-left"></div>

<div class="field-wrapper required">
	{% if form.last_name.errors %}
		{{ form.last_name.errors }}
	{% endif %}
	<label for="id_last_name" class="field-label">{% trans 'Last Name:'%}</label>
	{{ form.last_name }} 
</div>
<div class="clear-left"></div>

<div class="field-wrapper">
	{% if form.company.errors %}
		{{ form.company.errors }}
	{% endif %}
	<label for="id_company" class="field-label">{% trans 'Company:'%}</label>
	{{ form.company }}
</div>
<div class="clear-left"></div>

<div class="field-wrapper">
	{% if form.address.errors %}
		{{ form.address.errors }}
	{% endif %}
	<label for="id_address" class="field-label">{% trans 'Address:'%}</label>
	{{ form.address }}
</div>
<div class="clear-left"></div>

<div class="field-wrapper">
	{% if form.address2.errors %}
		{{ form.address2.errors }}
	{% endif %}
	<label for="id_address2" class="field-label">{% trans 'Address Line 2:'%}</label>
	{{ form.address2 }}
</div>
<div class="clear-left"></div>

<div class="field-wrapper">
	{% if form.city.errors %}
		{{ form.city.errors }}
	{% endif %}
	{% if form.state.errors %}
		{{ form.state.errors }}
	{% endif %}
	{% if form.zip_code %}
		{{ form.zip_code.errors }}
	{% endif %}
	<div  class="field-label">
	<label for="id_city">{% trans 'City'%}</label>
	/<label for="id_state">{% trans 'State'%}</label>
	/<label for="id_zip_code">{% trans 'Zip Code:'%}</label>
	</div>
	{{ form.city }} / {{ form.state }} / {{ form.zip_code }}
</div>
<div class="clear-left"></div>

<div class="field-wrapper">
	{% if form.country.errors %}
		{{ form.country.errors }}
	{% endif %}
	<label for="id_country" class="field-label">{% trans 'Country:'%}</label>
	{{ form.country }}
</div>
<div class="clear-left"></div>

<div class="field-wrapper">
	{% if form.phone.errors %}
		{{ form.phone.errors }}
	{% endif %}
	<label for="id_phone" class="field-label">{% trans 'Phone:'%}</label>
	{{ form.phone }}
</div>
<div class="clear-left"></div>

<div class="field-wrapper required">
	{% if form.email.errors %}
		{{ form.email.errors }}
	{% endif %}
	<label for="id_email" class="field-label">{% trans 'Email:'%}</label>
	{{ form.email }} 
</div>
<div class="clear-left"></div>

<div class="field-wrapper">
	{% if form.email_receipt.errors %}
		{{ form.email_receipt.errors }}
	{% endif %}
	<label for="id_email_receipt" class="field-label">{% trans 'Email Receipt?'%}</label>
	{{ form.email_receipt }} 
</div>
<div class="clear-left"></div>


<div class="field-wrapper">
	{% if form.referral_source.errors %}
		{{ form.referral_source.errors }}
	{% endif %}
	<label for="id_referral_source" class="field-label">{% trans 'Referred by:'%}</label>
	{{ form.referral_source }}
</div>
<div class="clear-left"></div>

<div class="field-wrapper">
	{% if form.comments.errors %}
		{{ form.comments.errors }}
	{% endif %}
	<label for="id_comments" class="field-label">{% trans 'Comments:'%}</label>
	{{ form.comments }}
</div>
<div class="clear-left"></div>

<div class="submitbutton">
<input type="submit" name="submit" value="Submit" />
</div>
</form>

</div>
{% endblock %}

templates/make_payments/add_confirm.html
{% extends "make_payments/base.html" %}

{% block title %}Add a Payment Confirmation{% endblock %}

{% block body %}
<div class="t">

<h1>Add a Payment Confirmation</h1>
<p>
Thank you for your payment!
</p>

</div>
{% endblock %}

templates/make_payments/base.html
{% extends "site_base.html" %}

{% block title %}Make a Payment{% endblock %}

{% block extra_body %}
{% endblock %}

templates/make_payments/invoice_search_result_line.html
{% load base_filters %}
{% load invoice_tags %}

<table width="100%">
   {% invoices_search_line_header request invoice '#66cc00' %}  
      
    {# display make payment info #} 
    <tr>
    	<td>MakePaymentID</td>
    	<td>First Name</td>
    	<td>Last Name</td>
    	<td>Date</td>
    	<td>Amount</td>
    	<td>Balance</td>
    </tr>
    
    {% if obj %} 
     <tr>
     	<td><a href="{% url make_payments.views.view obj.id %}">{{obj.id}}</a></td>
     	<td>{{obj.first_name}}</td>
     	<td>{{obj.last_name}}</td>
     	<td>{{obj.create_dt|date:'long'}}</td>
     	<td>{{obj.payment_amount|format_currency}}</td>
     	<td><div {% if invoice.balance > 0 %}class="body-copy-yellow"{% endif %}>{{invoice.balance|format_currency}}</div></td>
     </tr>  
   {% endif %}  
   
</table>

templates/make_payments/invoice_view_display.html
{% load base_filters %}

{# user info #}
<div class="invoice-view-box">
	{# make 3 blocks in the first box #}
	<div class="invoice-view-detail-left">
		{% if obj %}
			<a href="{% url make_payment.view obj.id %}" title="View Make Payment">{{ obj.id }}</a>
		{% else %}
			{{ invoice.object_id }}
		{% endif%}
	</div>
	
	<div class="invoice-view-detail-middle">
		<div class="invoice-item">
			{% if obj %}
				Payment Made by {{ obj.first_name }} {{obj.last_name}}
			{% else %}
				Make Payment Information not available
			{% endif%}
		</div>
		<div class="invoice-item">Phone: {{ obj.phone }}</div>
		<div class="invoice-item">Email: {{ obj.email }}</div>
		{% if obj.company %}
			<div class="invoice-item">Company: {{ obj.company }}</div>
		{% endif%}
		{% if obj.address or obj.address2 or obj.city or obj.state or obj.zip_code  %}
			<div class="invoice-item">Address: {{ obj.address }} {{ obj.address2 }}
				{{ obj.city }} {{ obj.state }} {{ obj.zip_code }}
			</div>
		{% endif%}
	</div>
	
	<div class="invoice-view-detail-right">
		Amount: {{ invoice.total|format_currency }}
	</div>
	<div class="clear-both"></div>
</div>

	

templates/make_payments/nav.html
{% load base_tags %}
{% load perm_tags %}

{% has_perm request.user site_settings.change_setting as can_edit_setting %}

{% if nav_object %}
	{% has_perm request.user make_payments.view_make_payment nav_object as can_view %}
{% endif %}

<div id="showh">
	<ul id="primary">
	
    {% if user.is_authenticated %}
	<li>
	    <a href="{% url dashboard %}" title="Tendenci Home Page">
		<img border="0" src="{{ STATIC_URL }}images/tendenci34x15.gif"
		alt="Tendenci User Home" align="top" width="34" height="15"></a>
	</li>
    {% endif %}

	<li>
		<span>Make Payments</span>
		<ul id="secondary">
			<li><a href="{% url make_payment.add %}">Make Payments:</a></li> 
			{% if can_edit_setting %}
				<li><a href="{% url settings.index "module" "invoices" %}">Settings</a></li>
			{% endif %}
			{% if nav_object %}
				<li><a href="{% url make_payment.view nav_object.pk %}">View</a></li>
			{% endif %}
			<li><a href="{% url make_payment.add %}">Add</a></li>
			
			
			{% if user.is_authenticated %}
			<li><a href="{% url auth_logout %}">Log Off</a></li> 
			{% endif %}
		</ul>
		
	</li>
	{% if MODULE_INVOICES_ENABLED %}
	<li><a href="{% url invoices %}">{{ MODULE_INVOICES_LABEL }}</a></li>
	{% endif %}
	{% if MODULE_NEWS_ENABLED %}
	<li><a href="{% url news %}">{{ MODULE_NEWS_LABEL }}</a></li>
	{% endif %}
	</ul>
</div>

templates/make_payments/view.html
{% extends "make_payments/base.html" %}
{% load i18n %}
{% load make_payment_tags %}
{% load base_filters %}

{% block title %}Make a Payment{% endblock %}

{% block extra_head %}
{{ block.super }}
<link rel="stylesheet" href="/site_media/static/css/make_payments.css">
<style>
	.make-payment-view{
		/*font-size: 12px;*/
	}
	.make-payment-view .label{
		float: left;
		text-align: right;
		width: 10em;
		padding-right: 1em;
	}
	.clear-left{
		clear: left;
	}
</style>
{% endblock %}

{% block body %}
<div class="t">
 {% make_payment_nav mp %}

<h1>View a Payment</h1>
<div class="make-payment-view">
<div class="label">Payment Amount:</div><div>{{ mp.payment_amount }}</div>
<div class="clear-left"></div>
<div class="label">Invoice ID:</div><div><a href="{% url invoices.views.view mp.invoice_id %}">{{ mp.invoice_id }}</a></div>
<div class="clear-left"></div>
{% if mp.user %}
<div class="label">User:</div><div><a href="{% url profile mp.user.username %}">{{mp.user.username }}</a></div>
<div class="clear-left"></div>
{% endif %}
<br />
<div class="label">Name:</div><div>{{ mp.first_name }} {{ mp.last_name }}</div>
<div class="clear-left"></div>
<div class="label">Company:</div><div>{{ mp.company }}</div>
<div class="clear-left"></div>
<div class="label">Address:</div><div>{{ mp.address }} {{ mp.address2 }} 
		{{ mp.city }} {{ mp.state }} {{ mp.zip_code }} {{ mp.country }}</div>
<div class="clear-left"></div>
<div class="label">Phone:</div><div>{{ mp.phone }}</div>
<div class="clear-left"></div>
<div class="label">Email:</div><div>{{ mp.email|obfuscate_email }}</div>
<div class="clear-left"></div>
<br />
<div class="label">Referred By:</div><div>{{ mp.referral_source }}</div>
<div class="clear-left"></div>
<div class="label">Comments:</div><div>{{ mp.comments|safe }}</div>
<div class="clear-left"></div>
<br />
<div class="label">Create Date:</div><div>{{ mp.create_dt|date:'long' }}</div>
<div class="clear-left"></div>
</div>
</div>
{% endblock %}