apps/articles/urls.py
from django.conf.urls.defaults import patterns, url
from articles.feeds import LatestEntriesFeed

urlpatterns = patterns('articles',                  
    url(r'^$', 'views.index', name="articles"),
    url(r'^search/$', 'views.search', name="article.search"),
    url(r'^print-view/(?P<slug>[\w\-\/]+)/$', 'views.print_view', name="article.print_view"),
    url(r'^add/$', 'views.add', name="article.add"),
    url(r'^edit/(?P<id>\d+)/$', 'views.edit', name="article.edit"),
    url(r'^edit/meta/(?P<id>\d+)/$', 'views.edit_meta', name="article.edit.meta"),
    url(r'^delete/(?P<id>\d+)/$', 'views.delete', name="article.delete"),
    url(r'^feed/$', LatestEntriesFeed(), name='article.feed'),
    url(r'^(?P<slug>[\w\-\/]+)/$', 'views.index', name="article"),
)

apps/base/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('base',
    url(r'^image-preview/(?P<app_label>\w+)/(?P<model>\w+)/(?P<id>\d+)/(?P<size>(\d+|\d+x\d+))/$', 'views.image_preview', name="image_preview"),
    url(r'^clear-cache/$', 'views.clear_cache', name='clear_cache'),
)

apps/search/urls.py
from django.conf.urls.defaults import patterns, url
from search.views import SearchView

urlpatterns = patterns('search.views',
    url(r'^$', SearchView(), name='haystack_search'),
)

urls.py
from os.path import join
from django.conf.urls.defaults import *
from django.conf import settings
from django.views.generic.simple import direct_to_template, redirect_to
from django.conf import settings

# Django admin
from django.contrib import admin
admin.autodiscover()

# App Registry
import registry
registry.autodiscover()

urlpatterns = patterns('',
    url(r'^$', direct_to_template, {"template": "homepage.html", }, name="home"),

    #Reports:
    (r'^reports/', include('reports.urls')),
    url(r'^event-logs/reports/summary/$', 'event_logs.views.event_summary_report', name='reports-events-summary'),
    url(r'^event-logs/reports/summary/([^/]+)/$', 'event_logs.views.event_source_summary_report', name='reports-events-source'),
    url(r'^users/reports/users-activity-top10/$', 'profiles.views.user_activity_report', name='reports-user-activity'),
    url(r'^users/reports/active-logins/$', 'profiles.views.user_access_report', name='reports-user-access'),
    url(r'^users/reports/admin/$', 'profiles.views.admin_users_report', name='reports-admin-users'),
    url(r'^users/reports/users-added/$', 'user_groups.views.users_added_report', {'kind': 'added'}, name='reports-user-added'),
    url(r'^users/reports/contacts-referral/$', 'user_groups.views.users_added_report', {'kind': 'referral'}, name='reports-contacts-referral'),
    url(r'^articles/reports/rank/$', 'articles.views.articles_report', name='reports-articles'),

    (r'^notifications/', include('notification.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^base/', include('base.urls')),
    (r'^avatar/', include('avatar.urls')),
    (r'^dashboard/', include('dashboard.urls')),
    (r'^categories/', include('categories.urls')),
    (r'^articles/', include('articles.urls')),
    (r'^entities/', include('entities.urls')),
    (r'^locations/', include('locations.urls')),
    (r'^pages/', include('pages.urls')),
    (r'^users/', include('profiles.urls')),
    (r'^photos/', include('photos.urls')),
    (r'^forms/', include('forms_builder.forms.urls')),
    (r'^events/', include('events.urls')),
    (r'^profiles/', include('profiles.urls')),
    (r'^groups/', include('user_groups.urls')),
    (r'^stories/', include('stories.urls')),
    (r'^invoices/', include('invoices.urls')),
    (r'^py/', include('make_payments.urls')),
    (r'^payments/', include('payments.urls')),
    (r'^accountings/', include('accountings.urls')),
    (r'^emails/', include('emails.urls')),
    (r'^newsletters/', include('newsletters.urls')),
    (r'^actions/', include('actions.urls')),
    (r'^rss/', include('rss.urls')),
    (r'^imports/', include('imports.urls')),
    #(r'^donations/', include('donations.urls')),
    (r'^news/', include('news.urls')),
    (r'^settings/', include('site_settings.urls')),
    (r'^files/', include('files.urls')),
    (r'^contacts/', include('contacts.urls')),
    (r'^accounts/', include('accounts.urls')),
    (r'^search/', include('search.urls')),
    (r'^event-logs/', include('event_logs.urls')),
    (r'^contributions/', include('contributions.urls')),
    (r'^theme-editor/', include('theme_editor.urls')),
    (r'^jobs/', include('jobs.urls')),
    (r'^directories/', include('directories.urls')),
    (r'^contact/', include('form_builder.urls')),
    (r'^sitemap.xml', include('sitemaps.urls')),
    (r'^help-files/', include('help_files.urls')),
    # third party (inside environment)
    (r'^tinymce/', include('tinymce.urls')),
    (r'^captcha/', include('captcha.urls')),
    (r'^redirects/', include('redirects.urls')),
    (r'^resumes/', include('resumes.urls')),
    (r'^mobile/', include('mobile.urls')),

    url(r'^sitemap/$', direct_to_template, {"template": "site_map.html", }, name="site_map"),
    url(r'^robots.txt', direct_to_template, {"template": "robots.txt", }, name="robots"),

    # legacy redirects
    url(r'^login/$', redirect_to, {'url': '/accounts/login/'}),
    
    # other t4 to t5 legacy redirects
    url(r'^en/', include('legacy.urls')),
)

handler500 = 'base.views.custom_error'

# serve static files
if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^site_media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': join(settings.PROJECT_ROOT, 'site_media')}),

        (r'^themes/%s/(?P<path>.*)$' % settings.SITE_THEME,
            'django.views.static.serve',
            {'document_root': settings.THEME_ROOT}),

        (r'^plugin-media/(?P<plugin>[^/]+)/(?P<path>.*)$',
            'base.views.plugin_static_serve'),
    )

# template tag testing environment
if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^tag-test/$', direct_to_template, {"template": "tag_test.html", }, name="tag_test"),
    )

# Local url patterns for development
try:
    from local_urls import extra_patterns
    urlpatterns += extra_patterns
except ImportError:
    pass

#PLUGINS:
import pluginmanager
urlpatterns += pluginmanager.get_url_patterns()

# tack on the pages pattern at the very end so let custom and software patterns
# happen first
pattern_pages = patterns('',
    # page view
    url(r'^(?P<slug>[\w\-\/]+)/$', 'pages.views.index', name="page"),  
)
urlpatterns += pattern_pages

apps/articles/models.py
import uuid
from datetime import datetime
from django.db import models
from django.utils.translation import ugettext_lazy as _

from tagging.fields import TagField
from base.fields import SlugField
from timezones.fields import TimeZoneField
from perms.models import TendenciBaseModel 
from articles.managers import ArticleManager
from tinymce import models as tinymce_models
from meta.models import Meta as MetaTags
from articles.module_meta import ArticleMeta
from entities.models import Entity

class Article(TendenciBaseModel):
    guid = models.CharField(max_length=40)
    slug = SlugField(_('URL Path'), unique=True)
    timezone = TimeZoneField(_('Time Zone'))
    headline = models.CharField(max_length=200, blank=True)
    summary = models.TextField(blank=True)
    body = tinymce_models.HTMLField()
    source = models.CharField(max_length=300, blank=True)
    first_name = models.CharField(_('First Name'), max_length=100, blank=True)
    last_name = models.CharField(_('Last Name'), max_length=100, blank=True)
    phone = models.CharField(max_length=50, blank=True)
    fax = models.CharField(max_length=50, blank=True)
    email = models.CharField(max_length=120, blank=True)
    website = models.CharField(max_length=300, blank=True)
    release_dt = models.DateTimeField(_('Release Date/Time'), null=True, blank=True)
    syndicate = models.BooleanField(_('Include in RSS feed'),)
    featured = models.BooleanField()
    design_notes = models.TextField(_('Design Notes'), blank=True)
    tags = TagField(blank=True)
  
    # for podcast feeds
    enclosure_url = models.CharField(_('Enclosure URL'), max_length=500, blank=True)
    enclosure_type = models.CharField(_('Enclosure Type'), max_length=120, blank=True)
    enclosure_length = models.IntegerField(_('Enclosure Length'), default=0)

    not_official_content = models.BooleanField(_('Official Content'), blank=True)
    entity = models.ForeignKey(Entity, null=True)

    # html-meta tags
    meta = models.OneToOneField(MetaTags, null=True)

    objects = ArticleManager()

    class Meta:
        permissions = (("view_article","Can view article"),)

    def get_meta(self, name):
        """
        This method is standard across all models that are
        related to the Meta model.  Used to generate dynamic
        methods coupled to this instance.
        """    
        return ArticleMeta().get_meta(self, name)
    
    @models.permalink
    def get_absolute_url(self):
        return ("article", [self.slug])

    def __unicode__(self):
        return self.headline
    
    def save(self, *args, **kwargs):
        if not self.id:
            self.guid = str(uuid.uuid1())
        super(self.__class__, self).save(*args, **kwargs)
    
    def age(self):
        return datetime.now() - self.create_dt

apps/base/forms.py
from re import compile
from django.core.validators import RegexValidator
from django.forms.fields import CharField
from django.utils.translation import ugettext_lazy as _

slug_re = compile(r'^[-\w\/]+$')
validate_slug = RegexValidator(slug_re, _(u"Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens."), 'invalid')

class SlugField(CharField):
    """
        New form slug field that validates with front slashes
        Straight copy from django with modifications
    """
    default_error_messages = {
        'invalid': _(u"Enter a valid 'slug' consisting of letters, numbers,"
                     u" underscores (_), front-slashes (/) or hyphens."),
    }
    default_validators = [validate_slug]
    
    def __init__(self, help_text=None, *args, **kwargs):
        super(SlugField, self).__init__(*args, **kwargs)
        
    def clean(self, value):
        value = self.to_python(value)     
        value = value.replace('//','')
        value = value.strip('/')

        self.validate(value)
        self.run_validators(value)
        
        return value
        

apps/base/views.py
# python
import Image as Pil

# django
from django.http import HttpResponse, HttpResponseNotFound
from django.contrib.contenttypes.models import ContentType
from django.core.cache import cache
from django.template import RequestContext
from django.shortcuts import render_to_response, redirect

# local
from base.cache import IMAGE_PREVIEW_CACHE

def image_preview(request, app_label, model, id,  size):
    """
        Grab all image link within a peice of content
        and generate thumbnails of largest image
    """    
    # get page object; protect size
    try:
        content_type = ContentType.objects.get(app_label=app_label, model=model)
        instance = content_type.get_object_for_this_type(id=id)
    except:
        return HttpResponseNotFound("Image not found.", mimetype="text/plain")

    response = cache.get(IMAGE_PREVIEW_CACHE + '.'.join([model, str(instance.id), size]))
    original_size = size
    
    if not response:
        from base.utils import parse_image_sources, make_image_object_from_url, image_rescale
        
        from pages.models import Page
        from articles.models import Article
        from news.models import News
 
        # set sizes
        size_min = (30,30)
        size_cap = (512,512)
        
        size_tuple = size.split('x')
        if len(size_tuple) == 2: size = int(size_tuple[0]), int(size_tuple[1])
        else: size = int(size), int(size)

        if size > size_cap: size = size_cap
    
        image_urls = []
        
        # siphon image urls; make fake image (starting image)
        if isinstance(instance,Page):
            image_urls = parse_image_sources(instance.content)
            
        if isinstance(instance,Article):
            image_urls = parse_image_sources(instance.body)
                  
        if isinstance(instance,News):
            image_urls = parse_image_sources(instance.body)
                                 
        image = Pil.new('RGBA',size_min)
    
        # find biggest image, dimension-wise
        for image_url in image_urls:
            image_candidate = make_image_object_from_url(image_url)
            if image_candidate:
                if image_candidate.size > image.size:
                    image = image_candidate

        if image.size[1] > size_min[1]:
        # rescale, convert-to true-colors; return response
    
            image = image_rescale(image, size)
            if image.mode != "RGB":
                image = image.convert("RGB")
    
            response = HttpResponse(mimetype='image/jpeg')
            
            image.save(response, "JPEG", quality=100)
            
            cache.set(IMAGE_PREVIEW_CACHE + '.'.join([model, str(instance.id), size]), response)
            return response
    
        else: # raise http 404 error (returns page not found)
            return HttpResponseNotFound("Image not found.", mimetype="text/plain")
    else:
        return response
    
def custom_error(request, template_name="500.html"):
    return render_to_response(template_name, {}, context_instance=RequestContext(request))

def plugin_static_serve(request, plugin, path, show_indexes=False):
    """
    Serve static files below a given point in the directory structure.

    To use, put a URL pattern such as::

        (r'^(?P<path>.*)$', 'django.views.static.serve', {'document_root' : '/path/to/my/files/'})

    in your URLconf. You must provide the ``document_root`` param. You may
    also set ``show_indexes`` to ``True`` if you'd like to serve a basic index
    of the directory.  This index view will use the template hardcoded below,
    but if you'd like to override it, you can create a template called
    ``static/directory_index.html``.
    """

    import mimetypes
    import os
    import posixpath
    import stat
    import urllib
    from email.Utils import parsedate_tz, mktime_tz

    from django.http import Http404, HttpResponse, HttpResponseRedirect, HttpResponseNotModified
    from django.utils.http import http_date
    from django.views.static import was_modified_since, directory_index

    import settings

    document_root = os.path.join(settings.PROJECT_ROOT,'plugins',plugin,'media')

    # Clean up given path to only allow serving files below document_root.
    path = posixpath.normpath(urllib.unquote(path))
    path = path.lstrip('/')
    newpath = ''
    for part in path.split('/'):
        if not part:
            # Strip empty path components.
            continue
        drive, part = os.path.splitdrive(part)
        head, part = os.path.split(part)
        if part in (os.curdir, os.pardir):
            # Strip '.' and '..' in path.
            continue
        newpath = os.path.join(newpath, part).replace('\\', '/')

    if newpath and path != newpath:
        return HttpResponseRedirect(newpath)
    fullpath = os.path.join(document_root, newpath)

    if os.path.isdir(fullpath):
        if show_indexes:
            return directory_index(newpath, fullpath)
        raise Http404("Directory indexes are not allowed here.")
    if not os.path.exists(fullpath):
        raise Http404('"%s" does not exist' % fullpath)

    # Respect the If-Modified-Since header.
    statobj = os.stat(fullpath)
    mimetype = mimetypes.guess_type(fullpath)[0] or 'application/octet-stream'
    if not was_modified_since(request.META.get('HTTP_IF_MODIFIED_SINCE'),
                              statobj[stat.ST_MTIME], statobj[stat.ST_SIZE]):
        return HttpResponseNotModified(mimetype=mimetype)
    contents = open(fullpath, 'rb').read()
    response = HttpResponse(contents, mimetype=mimetype)
    response["Last-Modified"] = http_date(statobj[stat.ST_MTIME])
    response["Content-Length"] = len(contents)
    return response
    
def clear_cache(request):
    cache.clear()
    return redirect('dashboard')

templates/articles/add.html
{% extends "articles/base.html" %}
{% load article_tags %}
{% load perm_tags %}
{% load styled_forms %}

{% block title %}{% firstof MODULE_ARTICLES_LABEL 'Article' %} Add{% endblock %}

{% block extra_head %}
{{ block.super }}
<link rel="stylesheet" href="{{ STATIC_URL }}css/jquery-ui/jquery-ui-1.8.2.custom.css">
<link rel="stylesheet" href="{{ STATIC_URL }}css/timepicker.css" />
<link rel="stylesheet" href="{{ STATIC_URL }}css/articles.css">
<script type="text/javascript" src="{{ STATIC_URL }}tinymce/tiny_mce.js"></script>
{% endblock %}

{% block body %}

<div class="t">
    {% article_nav request.user %}
	
    <h1>{% firstof MODULE_ARTICLES_LABEL 'Article' %} Add</h1>

    <div class="article-wrap">  
    	<form action="{% url article.add %}" method="post">
    	<div class="forms">
			{{ form|styled_form }}
        	<input type="submit" value="Add {% firstof MODULE_ARTICLES_LABEL 'Article' %}" />
		</div>
        </form>
    </div>

</div>
{% endblock %}

{% block extra_body %}
    {{ block.super }}
	<script type="text/javascript" src="{{ STATIC_URL }}js/global/tinymce.event_handlers.js"></script>
	<script type="text/javascript" src="{{ STATIC_URL }}js/jquery-ui-1.8.2.custom.min.js"></script>
	<script src="{{ STATIC_URL }}js/jquery.time.picker.js" type="text/javascript"></script>
	<script type="text/javascript" src="{{ STATIC_URL }}js/slug.js"></script>
	<script type="text/javascript">
		var slugit = new Slugify({
			input_element : 'input#id_headline',
			slug_element : 'input#id_slug',
			submit_element : 'input[type="submit"]',
			help: false,
			limit : 150
		});
	</script>
	<script type="text/javascript">
		$(".datepicker").datepicker({ dateFormat: 'yy-mm-dd' });
		$('.timepicker').timePicker({
		  show24Hours: false,
		  step: 15
		});
	</script>
{% endblock %}

templates/articles/base.html
{% extends "site_base.html" %}

{% block title %}{{SITE_GLOBAL_SITEPRIMARYKEYWORDS }}: {% firstof MODULE_ARTICLES_LABEL 'Articles' %} for  {{SITE_GLOBAL_SITEDISPLAYNAME }} in {{SITE_GLOBAL_SITEGEOGRAPHICLOCATION }}{% endblock %}
{% block meta_description %}{{SITE_GLOBAL_SITEPRIMARYKEYWORDS }}: {% firstof MODULE_ARTICLES_LABEL 'Articles' %} and White Papers for {{SITE_GLOBAL_SITEDISPLAYNAME }} in {{SITE_GLOBAL_SITEGEOGRAPHICLOCATION }}{% endblock %}
{% block meta_keywords %}{% firstof MODULE_ARTICLES_LABEL 'Articles' %},  {{SITE_GLOBAL_SITEGEOGRAPHICLOCATION }}, {{SITE_GLOBAL_SITEDISPLAYNAME }}, white papers, {{SITE_GLOBAL_SITESECONDARYKEYWORDS }}{% endblock %}

{% block messages %}{{ block.super }}{% endblock %}

templates/articles/delete.html
{% block body %}
<h1>{% firstof MODULE_ARTICLES_LABEL 'Article' %} Delete Page</h1>
<div class="back-to-search"><a href="{% url article.search %}">&laquo; Back to articles search</a></div>
{% endblock %}

templates/articles/edit-meta.html
{% extends "articles/base.html" %}
{% load article_tags %}
{% load styled_forms %}

{% block title %}{% firstof MODULE_ARTICLES_LABEL 'Article' %} Edit Meta Information{% endblock %}

{% block extra_head %}
{{ block.super }}
<link rel="stylesheet" href="{{ STATIC_URL }}css/articles.css">
{% endblock %}

{% block body %}
<div class="t">

    {% article_nav user %}
    <h1>{% firstof MODULE_ARTICLES_LABEL 'Article' %} Meta Information for<br />
    {{ article.headline }}</h1>

    <div class="article-wrap">
		<div class="options">
             <div class="quick-options">
				{% article_options request.user article %} 	       
             </div>
		</div>
    	<form action="{% url article.edit.meta article.pk %}" method="post">
    	<div class="forms">
            {{ form|styled_form }}
        	<input type="submit" value="Save Changes" />
			 or <a href="javascript:history.go(-1);">Cancel</a>
		</div>
        </form>
    </div>
</div>
{% endblock %}

{% block extra_body %}
    {{ block.super }}
    <script type="text/javascript">
		$(document).ready(function(){
			// delete confirmation
			$('.delete').click(function(){
				var delete_article = confirm('Permenantly delete {% firstof MODULE_ARTICLES_LABEL 'Article' %}?');	// confirm
				if(delete_article) $('.t').find('form[name="article-delete"]').submit() // delete: if OK
				return false;	// cancel
			});
		});
    </script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/global/dropdown.js"></script>
	<script type="text/javascript">
	var iconrow = new dropdown({
		container:	'more-options-wrap',
		trigger:	'more-options-trigger',
		target:		'more-options-target'
	});
	</script>
{% endblock %}

templates/articles/edit.html
{% extends "articles/base.html" %}
{% load article_tags %}
{% load perm_tags %}
{% load styled_forms %}

{% block title %}{% firstof MODULE_ARTICLES_LABEL 'Article' %} Edit{% endblock %}

{% block extra_head %}
{{ block.super }}
<link rel="stylesheet" href="{{ STATIC_URL }}css/jquery-ui/jquery-ui-1.8.2.custom.css">
<link rel="stylesheet" href="{{ STATIC_URL }}css/timepicker.css" />
<link rel="stylesheet" href="{{ STATIC_URL }}css/articles.css">
<script type="text/javascript" src="{{ STATIC_URL }}tinymce/tiny_mce.js"></script>
{% endblock %}

{% block body %}
<div class="t">
    {% article_nav request.user article %}

    <h1>{% firstof MODULE_ARTICLES_LABEL 'Article' %} Edit</h1>

    <div class="article-wrap">
		<div class="options">
             <div class="quick-options">
				{% article_options request.user article %} 	       
             </div>
		</div>
    	<form action="{% url article.edit article.pk %}" method="post">
    	<div class="forms">
 			{{ form|styled_form }}
        	<input type="submit" value="Save Changes" />
		</div>
        </form>
    </div>
</div>
{% endblock %}

{% block extra_body %}
    {{ block.super }}
    <script type="text/javascript" src="{{ STATIC_URL }}js/global/tinymce.event_handlers.js"></script>
	<script type="text/javascript" src="{{ STATIC_URL }}js/jquery-ui-1.8.2.custom.min.js"></script>
	<script src="{{ STATIC_URL }}js/jquery.time.picker.js" type="text/javascript"></script>
    <script type="text/javascript">
		$(document).ready(function(){
			// delete confirmation
			$('.delete').click(function(){
				var delete_object = confirm("Permenantly delete {% firstof MODULE_ARTICLES_LABEL 'Article' %}?");	// confirm
				if(delete_object) $('form[name="article-delete"]').submit()
				return false;	// cancel
			});
		});
    </script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/global/dropdown.js"></script>
	<script type="text/javascript">
	var iconrow = new dropdown({
		container:	'more-options-wrap',
		trigger:	'more-options-trigger',
		target:		'more-options-target'
	});
	</script>
	<script type="text/javascript">
		$(".datepicker").datepicker({ dateFormat: 'yy-mm-dd' });
		$('.timepicker').timePicker({
		  show24Hours: false,
		  step: 15
		});
	</script>
{% endblock %}

templates/articles/index.html
<h1>{% firstof MODULE_ARTICLES_LABEL 'Articles' %} Index Page</h1>

<ul>
	<li><a href="{% url article.search %}">Search</a></li>
	<li><a href="{% url article.view %}">View</a></li>
	<li><a href="{% url article.print_view %}">Print View</a></li>
	<li><a href="{% url article.edit %}">Edit</a></li>
	<li><a href="{% url article.delete %}">Delete</a></li>
</ul>

templates/articles/nav.html
{% load base_tags %}
{% load perm_tags %}

{% has_perm user site_settings.change_setting as can_edit_setting %}
{% has_perm user articles.add_article as can_add_article %}

{% if nav_object %}
	{% has_perm user articles.view_article nav_object as can_view_article %}
	{% has_perm user articles.change_article nav_object as can_edit_article %}
	{% has_perm user articles.delete_article nav_object as can_delete_article %}
{% else %}
	{% has_perm user articles.view_article as can_view_article %}
	{% has_perm user articles.change_article as can_edit_article %}
	{% has_perm user articles.delete_article as can_delete_article %}
{% endif %}

<div id="showh">
	<ul id="primary">
	
    {% if user.is_authenticated %}
	<li>
	    <a href="{% url dashboard %}" title="Tendenci Home Page">
		<img border="0" src="{{ STATIC_URL }}images/tendenci34x15.gif"
		alt="Tendenci User Home" align="top" width="34" height="15"></a>
	</li>
    {% endif %}

	<li>
		<span>{% firstof MODULE_ARTICLES_LABEL 'Article' %}</span>
		<ul id="secondary">
			<li><a href="{% url articles %}">{% firstof MODULE_ARTICLES_LABEL 'Article' %}:</a></li> 
			{% if can_edit_setting %}
				<li><a href="{% url settings.index "module" "articles" %}">Settings</a></li>
			{% endif %}
			{% if nav_object %}
				{% if can_view_article %}
				<li><a href="{{ nav_object.get_absolute_url }}">View</a></li>
				{% endif %}
				{% if can_edit_article %}
				<li><a href="{% url article.edit nav_object.pk %}">Edit</a></li>
				<li><a href="{% url article.edit.meta nav_object.pk %}">Edit Meta</a></li>
				<li><a href="{% url category.update nav_object.opt_app_label nav_object.opt_module_name nav_object.pk %}">Edit Categories</a></li>
				{% endif %}
			{% endif %}
			<li><a href="{% url article.search %}">Search</a></li>
			{% if can_add_article %}
			<li><a href="{% url article.add %}">Add</a></li>
			{% endif %}

			{% if user.is_authenticated %}
			<li><a href="{% url auth_logout %}">Log Off</a></li> 
			{% endif %}
		</ul>
		
	</li>
	{% if MODULE_NEWS_ENABLED %}
	<li><a href="{% url news %}">{% firstof MODULE_NEWS_LABEL 'News' %}</a></li>
	{% endif %}
	</ul>
</div>

templates/articles/options.html
{% load base_tags %}
{% load perm_tags %}

{% has_perm user articles.change_article opt_object as can_edit %}
{% has_perm user articles.delete_article opt_object as can_delete %}

<div class="t-iconrow">

	{% if can_edit %}
	<span>{{ opt_object.status_detail|capfirst }}</span>
	{% endif %}

	<a class="option-link print" href="{% url article.print_view opt_object.slug %}">Print</a>

	{% if can_edit %}
		<a class="option-link edit" href="{% url article.edit opt_object.pk %}">Edit</a>
	{% endif %}

 {% if can_edit %}
	  <div class="more-options-wrap">
	    <a href="javascript:;" class="more-options-trigger">More options <small>&#9660;</small></a>
	    <div class="more-options-target">
	        <ul>
				<li class="divider">
				  <a href="{% url article.edit.meta opt_object.pk %}">Edit Meta</a>
				</li>
				
				<li>
				{% if opt_object.object %}
					<a href="{% url category.update opt_object.object.opt_app_label opt_object.object.opt_module_name opt_object.pk %}">Edit Categories</a>
				{% else %}
					<a href="{% url category.update opt_object.opt_app_label opt_object.opt_module_name opt_object.pk %}">Edit Categories</a>
				{% endif %}
				</li>
				
				{% if can_delete %}
					<li>
						<a class="option-link delete" href="{% url article.delete opt_object.pk %}">Delete</a>
					</li>				
				{% endif %}
			 </ul>
	        </div>
	  </div>
  {% endif %}
</div>

templates/articles/search-form.html
<form class="search-form" action="{% url article.search %}" method="get">
<input type="text" name="q" value="{{ request.GET.q|striptags }}" />
<input type="submit" value="Search" />
</form>