apps/base/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('base',
    url(r'^image-preview/(?P<app_label>\w+)/(?P<model>\w+)/(?P<id>\d+)/(?P<size>(\d+|\d+x\d+))/$', 'views.image_preview', name="image_preview"),
    url(r'^clear-cache/$', 'views.clear_cache', name='clear_cache'),
)

apps/memberships/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns("memberships.views",


    # memberships
    url(r"^memberships/(?P<id>\d+)/$", "membership_details", name="membership.details"),

    # entries
    url(r"^entries/$", "application_entries", name="membership.application_entries"),
    url(r"^entries/(?P<id>\d+)/$", "application_entries", name="membership.application_entries"),
    url(r"^entries/search/$", "application_entries_search", name="membership.application_entries_search"),

    # application
    url(r"^confirmation/(?P<hash>[\w]+)/$", "application_confirmation", name="membership.application_confirmation"),
    url(r"^(?P<slug>[\w\-]+)/(?P<cmb_id>\d+)?/?$", "application_details", name="membership.application_details"),
    url(r"^(?P<slug>[\w\-]+)/corp-pre/(?P<cmb_id>\d+)?/?$", "application_details_corp_pre", name="membership.application_details_corp_pre"),
    
)

apps/search/urls.py
from django.conf.urls.defaults import patterns, url
from search.views import SearchView

urlpatterns = patterns('search.views',
    url(r'^$', SearchView(), name='haystack_search'),
)

urls.py
from os.path import join
from django.conf.urls.defaults import *
from django.conf import settings
from django.views.generic.simple import direct_to_template, redirect_to
from django.conf import settings

# Django admin
from django.contrib import admin
admin.autodiscover()

# App Registry
import registry
registry.autodiscover()

urlpatterns = patterns('',
    url(r'^$', direct_to_template, {"template": "homepage.html", }, name="home"),

    #Reports:
    (r'^reports/', include('reports.urls')),
    url(r'^event-logs/reports/summary/$', 'event_logs.views.event_summary_report', name='reports-events-summary'),
    url(r'^event-logs/reports/summary/([^/]+)/$', 'event_logs.views.event_source_summary_report', name='reports-events-source'),
    url(r'^users/reports/users-activity-top10/$', 'profiles.views.user_activity_report', name='reports-user-activity'),
    url(r'^users/reports/active-logins/$', 'profiles.views.user_access_report', name='reports-user-access'),
    url(r'^users/reports/admin/$', 'profiles.views.admin_users_report', name='reports-admin-users'),
    url(r'^users/reports/users-added/$', 'user_groups.views.users_added_report', {'kind': 'added'}, name='reports-user-added'),
    url(r'^users/reports/contacts-referral/$', 'user_groups.views.users_added_report', {'kind': 'referral'}, name='reports-contacts-referral'),
    url(r'^articles/reports/rank/$', 'articles.views.articles_report', name='reports-articles'),

    (r'^notifications/', include('notification.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^base/', include('base.urls')),
    (r'^avatar/', include('avatar.urls')),
    (r'^dashboard/', include('dashboard.urls')),
    (r'^categories/', include('categories.urls')),
    (r'^articles/', include('articles.urls')),
    (r'^entities/', include('entities.urls')),
    (r'^locations/', include('locations.urls')),
    (r'^pages/', include('pages.urls')),
    (r'^users/', include('profiles.urls')),
    (r'^photos/', include('photos.urls')),
    (r'^forms/', include('forms_builder.forms.urls')),
    (r'^events/', include('events.urls')),
    (r'^profiles/', include('profiles.urls')),
    (r'^groups/', include('user_groups.urls')),
    (r'^stories/', include('stories.urls')),
    (r'^invoices/', include('invoices.urls')),
    (r'^py/', include('make_payments.urls')),
    (r'^payments/', include('payments.urls')),
    (r'^accountings/', include('accountings.urls')),
    (r'^emails/', include('emails.urls')),
    (r'^newsletters/', include('newsletters.urls')),
    (r'^actions/', include('actions.urls')),
    (r'^rss/', include('rss.urls')),
    (r'^imports/', include('imports.urls')),
    #(r'^donations/', include('donations.urls')),
    (r'^news/', include('news.urls')),
    (r'^settings/', include('site_settings.urls')),
    (r'^files/', include('files.urls')),
    (r'^contacts/', include('contacts.urls')),
    (r'^accounts/', include('accounts.urls')),
    (r'^search/', include('search.urls')),
    (r'^event-logs/', include('event_logs.urls')),
    (r'^contributions/', include('contributions.urls')),
    (r'^theme-editor/', include('theme_editor.urls')),
    (r'^jobs/', include('jobs.urls')),
    (r'^directories/', include('directories.urls')),
    (r'^contact/', include('form_builder.urls')),
    (r'^sitemap.xml', include('sitemaps.urls')),
    (r'^help-files/', include('help_files.urls')),
    # third party (inside environment)
    (r'^tinymce/', include('tinymce.urls')),
    (r'^captcha/', include('captcha.urls')),
    (r'^redirects/', include('redirects.urls')),
    (r'^resumes/', include('resumes.urls')),
    (r'^mobile/', include('mobile.urls')),

    url(r'^sitemap/$', direct_to_template, {"template": "site_map.html", }, name="site_map"),
    url(r'^robots.txt', direct_to_template, {"template": "robots.txt", }, name="robots"),

    # legacy redirects
    url(r'^login/$', redirect_to, {'url': '/accounts/login/'}),
    
    # other t4 to t5 legacy redirects
    url(r'^en/', include('legacy.urls')),
)

handler500 = 'base.views.custom_error'

# serve static files
if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^site_media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': join(settings.PROJECT_ROOT, 'site_media')}),

        (r'^themes/%s/(?P<path>.*)$' % settings.SITE_THEME,
            'django.views.static.serve',
            {'document_root': settings.THEME_ROOT}),

        (r'^plugin-media/(?P<plugin>[^/]+)/(?P<path>.*)$',
            'base.views.plugin_static_serve'),
    )

# template tag testing environment
if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^tag-test/$', direct_to_template, {"template": "tag_test.html", }, name="tag_test"),
    )

# Local url patterns for development
try:
    from local_urls import extra_patterns
    urlpatterns += extra_patterns
except ImportError:
    pass

#PLUGINS:
import pluginmanager
urlpatterns += pluginmanager.get_url_patterns()

# tack on the pages pattern at the very end so let custom and software patterns
# happen first
pattern_pages = patterns('',
    # page view
    url(r'^(?P<slug>[\w\-\/]+)/$', 'pages.views.index', name="page"),  
)
urlpatterns += pattern_pages

plugins/donations/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from invoices.models import Invoice
from donations.managers import DonationManager

class Donation(models.Model):
    guid = models.CharField(max_length=50)
    user = models.ForeignKey(User, null=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    company = models.CharField(max_length=50, default='', blank=True, null=True)
    address = models.CharField(max_length=100, default='', blank=True, null=True)
    address2 = models.CharField(_('address line 2'), max_length=100, default='', blank=True, null=True)
    city = models.CharField(max_length=50, default='', blank=True, null=True)
    state = models.CharField(max_length=50, default='', blank=True, null=True)
    zip_code = models.CharField(max_length=50, default='', blank=True, null=True)
    country = models.CharField(max_length=50, default='', blank=True, null=True)
    email = models.CharField(max_length=50)
    phone = models.CharField(max_length=50)
    referral_source = models.CharField(_('referred by'), max_length=200, default='', blank=True, null=True)
    comments = models.TextField(blank=True, null=True)
    donation_amount = models.DecimalField(max_digits=10, decimal_places=2)
    allocation = models.CharField(max_length=150, default='', blank=True,  null=True)
    payment_method = models.CharField(max_length=50, default='cc')
    invoice = models.ForeignKey(Invoice, blank=True, null=True)
    create_dt = models.DateTimeField(auto_now_add=True)
    creator = models.ForeignKey(User, null=True,  related_name="donation_creator")
    creator_username = models.CharField(max_length=50, null=True)
    owner = models.ForeignKey(User, null=True, related_name="donation_owner")
    owner_username = models.CharField(max_length=50, null=True)
    status_detail = models.CharField(max_length=50, default='estimate')
    status = models.BooleanField(default=True)
    
    objects = DonationManager()
    
    def save(self, user=None, *args, **kwargs):
        if not self.id:
            self.guid = str(uuid.uuid1())
            if user and user.id:
                self.creator=user
                self.creator_username=user.username
        if user and user.id:
            self.owner=user
            self.owner_username=user.username
            
        super(self.__class__, self).save(*args, **kwargs)
        
    # Called by payments_pop_by_invoice_user in Payment model.
    def get_payment_description(self, inv):
        """
        The description will be sent to payment gateway and displayed on invoice.
        If not supplied, the default description will be generated.
        """
        return 'Tendenci Invoice %d Payment for Donation %d' % (
            inv.id,
            inv.object_id,
        )
        
    def make_acct_entries(self, user, inv, amount, **kwargs):
        """
        Make the accounting entries for the donation sale
        """
        from accountings.models import Acct, AcctEntry, AcctTran
        from accountings.utils import make_acct_entries_initial, make_acct_entries_closing
        
        ae = AcctEntry.objects.create_acct_entry(user, 'invoice', inv.id)
        if not inv.is_tendered:
            make_acct_entries_initial(user, ae, amount)
        else:
            # payment has now been received
            make_acct_entries_closing(user, ae, amount)
            
            # #CREDIT donation SALES
            acct_number = self.get_acct_number()
            acct = Acct.objects.get(account_number=acct_number)
            AcctTran.objects.create_acct_tran(user, ae, acct, amount*(-1)) 
            
    def get_acct_number(self, discount=False):
        if discount:
            return 465100
        else:
            return 405100
            
    def auto_update_paid_object(self, request, payment):
        """
        Update the object after online payment is received.
        """
        # email to admin
        try:
            from notification import models as notification
        except:
            notification = None
        from perms.utils import get_notice_recipients
        
        recipients = get_notice_recipients('module', 'donations', 'donationsrecipients')
        if recipients:
            if notification:
                extra_context = {
                    'donation': self,
                    'invoice': payment.invoice,
                    'request': request,
                }
                notification.send_emails(recipients,'donation_added', extra_context)

apps/base/forms.py
from re import compile
from django.core.validators import RegexValidator
from django.forms.fields import CharField
from django.utils.translation import ugettext_lazy as _

slug_re = compile(r'^[-\w\/]+$')
validate_slug = RegexValidator(slug_re, _(u"Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens."), 'invalid')

class SlugField(CharField):
    """
        New form slug field that validates with front slashes
        Straight copy from django with modifications
    """
    default_error_messages = {
        'invalid': _(u"Enter a valid 'slug' consisting of letters, numbers,"
                     u" underscores (_), front-slashes (/) or hyphens."),
    }
    default_validators = [validate_slug]
    
    def __init__(self, help_text=None, *args, **kwargs):
        super(SlugField, self).__init__(*args, **kwargs)
        
    def clean(self, value):
        value = self.to_python(value)     
        value = value.replace('//','')
        value = value.strip('/')

        self.validate(value)
        self.run_validators(value)
        
        return value
        

plugins/donations/forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from donations.models import Donation
from donations.utils import get_allocation_choices, get_payment_method_choices, get_preset_amount_choices
from site_settings.utils import get_setting

class DonationForm(forms.ModelForm):
    # get the payment_method choices from settings
    donation_amount = forms.CharField(error_messages={'required': 'Please enter the donation amount.'})
    payment_method = forms.CharField(error_messages={'required': 'Please select a payment method.'},
                                     widget=forms.RadioSelect(choices=(('check-paid', 'Paid by Check'), 
                                                              ('cc', 'Make Online Payment'),)), initial='cc', )
    company = forms.CharField(max_length=50, required=False, widget=forms.TextInput(attrs={'size':'30'}))
    address = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'size':'35'}))
    state = forms.CharField(max_length=50, required=False,  widget=forms.TextInput(attrs={'size':'5'}))
    zip_code = forms.CharField(max_length=20, required=False, widget=forms.TextInput(attrs={'size':'10'}))
    referral_source = forms.CharField(max_length=200, required=False, widget=forms.TextInput(attrs={'size':'40'}))
    email = forms.EmailField(help_text='A valid e-mail address, please.')
    email_receipt = forms.BooleanField(initial=True)
    comments = forms.CharField(max_length=1000, required=False,
                               widget=forms.Textarea(attrs={'rows':'3'}))
    allocation = forms.ChoiceField()
    
    class Meta:
        model = Donation
        fields = ('donation_amount',
                  'payment_method',
                  'first_name',
                  'last_name',
                  'company',
                  'address',
                  'address2',
                  'city',
                  'state',
                  'zip_code',
                  'country',
                  'phone',
                  'email',
                  'email_receipt',
                  'allocation',
                  'referral_source',
                  'comments',
                  )
        
    def __init__(self, *args, **kwargs):
        if 'user' in kwargs:
            self.user = kwargs.pop('user', None)
        else:
            self.user = None
        super(DonationForm, self).__init__(*args, **kwargs)
        # populate the user fields
        if self.user and self.user.id:
            self.fields['first_name'].initial = self.user.first_name
            self.fields['last_name'].initial = self.user.last_name
            self.fields['email'].initial = self.user.email
            try:
                profile = self.user.get_profile()
                if profile:
                    self.fields['company'].initial = profile.company
                    self.fields['address'].initial = profile.address
                    self.fields['address2'].initial = profile.address2
                    self.fields['city'].initial = profile.city
                    self.fields['state'].initial = profile.state
                    self.fields['zip_code'].initial = profile.zipcode
                    self.fields['country'].initial = profile.country
                    self.fields['phone'].initial = profile.phone
            except:
                pass
            
        self.fields['payment_method'].widget = forms.RadioSelect(choices=get_payment_method_choices(self.user))
        allocation_str = get_setting('module', 'donations', 'donationsallocations')
        if allocation_str:
            self.fields['allocation'].choices = get_allocation_choices(self.user, allocation_str)
        else:
            del self.fields['allocation']
        preset_amount_str = (get_setting('module', 'donations', 'donationspresetamounts')).strip('')
        if preset_amount_str:
            self.fields['donation_amount'] = forms.ChoiceField(choices=get_preset_amount_choices(preset_amount_str))
            
            
    def clean_donation_amount(self):
        #raise forms.ValidationError(_(u'This username is already taken. Please choose another.'))
        try:
            if float(self.cleaned_data['donation_amount']) <= 0:
                raise forms.ValidationError(_(u'Please enter a positive number'))
        except:
            raise forms.ValidationError(_(u'Please enter a numeric positive number'))                       
        return self.cleaned_data['donation_amount']
        

plugins/donations/templates/donations/add.html
{% extends "donations/base.html" %}
{% load i18n %}
{% load donation_tags %}

{% block title %}Make a Donation{% endblock %}

{% block extra_head %}
{{ block.super }}
<link rel="stylesheet" href="/site_media/static/css/donations.css">
{% endblock %}

{% block body %}
<div class="t">
{% donation_nav request.user %}
<div class="donation-add">

<h1>Make a Donation</h1>
<p>Complete the form below to make a donation. 
The required fields are marked with <em class="body-copy-alert">*</em>. <br />Thank You!</p>
<br />
	{% if form.errors %}
		<div class="errors">
			<p>Please review the fields below. Thank you.</p>
			<ul>
			{% for field in form %}
				{% if field.errors %}
					<li><a href="javascript:;">{{ field.label_tag }}</a></li>	
				{% endif %}
			{% endfor %}
			</ul>
		</div>
	{% endif %}
	
<form method="post" action=".">
<div class="field-wrapper">
	{% if form.donation_amount.errors %}
		<div class="errs">{{ form.donation_amount.errors }}</div>
	{% endif %}
	<label for="id_donation_amount" class="field-label"><em class="body-copy-alert">*</em> 
	{% trans 'Donation Amount'%} ({{currency_symbol}})</label>
	{{ form.donation_amount }}
</div>
<div class="clear-left"></div>

{% if form.allocation %}
	<div class="field-wrapper">
		{% if form.form.allocation.errors %}
			<div class="errs">{{ form.form.allocation.errors }}</div>
		{% endif %}
		<label for="id_form.allocation" class="field-label"> 
		{% trans 'Donate to'%}</label>
		{{ form.allocation }}
	</div>
	<div class="clear-left"></div>

{% endif %}

<div class="field-wrapper">
	{% if form.payment_method.errors %}
		<div class="errs">{{ form.payment_method.errors }}</div>
	{% endif %}
	<label for="id_payment_method" class="field-label"><em class="body-copy-alert">*</em> 
	{% trans 'Payment Method'%}</label>
	<div class="payment-method-list">{{ form.payment_method }}</div>
</div>
<div class="clear-left"></div>

<div class="section-header">
	Billing Information
</div>

<div class="field-wrapper">
	{% if form.first_name.errors %}
		<div class="errs">{{ form.first_name.errors }}</div>
	{% endif %}
	<label for="id_first_name" class="field-label"><em class="body-copy-alert">*</em> 
	{% trans 'First Name'%}</label>
	{{ form.first_name }} 
</div>
<div class="clear-left"></div>

<div class="field-wrapper">
	{% if form.last_name.errors %}
		<div class="errs">{{ form.last_name.errors }}</div>
	{% endif %}
	<label for="id_last_name" class="field-label"><em class="body-copy-alert">*</em> 
	{% trans 'Last Name'%}</label>
	{{ form.last_name }} 
</div>
<div class="clear-left"></div>

<div class="field-wrapper">
	{% if form.company.errors %}
		<div class="errs">{{ form.company.errors }}</div>
	{% endif %}
	<label for="id_company" class="field-label">{% trans 'Company'%}</label>
	{{ form.company }}
</div>
<div class="clear-left"></div>

<div class="field-wrapper">
	{% if form.address.errors %}
		<div class="errs">{{ form.address.errors }}</div>
	{% endif %}
	<label for="id_address" class="field-label">{% trans 'Address'%}</label>
	{{ form.address }}
</div>
<div class="clear-left"></div>

<div class="field-wrapper">
	{% if form.address2.errors %}
		<div class="errs">{{ form.address2.errors }}</div>
	{% endif %}
	<label for="id_address2" class="field-label">{% trans 'Address Line 2'%}</label>
	{{ form.address2 }}
</div>
<div class="clear-left"></div>

<div class="field-wrapper">
	{% if form.city.errors %}
		{{ form.city.errors }}
	{% endif %}
	{% if form.state.errors %}
		{{ form.state.errors }}
	{% endif %}
	{% if form.zip_code %}
		{{ form.zip_code.errors }}
	{% endif %}
	<div  class="field-label">
	<label for="id_city">{% trans 'City'%}</label>
	/<label for="id_state">{% trans 'State'%}</label>
	/<label for="id_zip_code">{% trans 'Zip Code'%}</label>
	</div>
	{{ form.city }} / {{ form.state }} / {{ form.zip_code }}
</div>
<div class="clear-left"></div>

<div class="field-wrapper">
	{% if form.country.errors %}
		<div class="errs">{{ form.country.errors }}</div>
	{% endif %}
	<label for="id_country" class="field-label">{% trans 'Country'%}</label>
	{{ form.country }}
</div>
<div class="clear-left"></div>

<div class="field-wrapper">
	{% if form.phone.errors %}
		<div class="errs">{{ form.phone.errors }}</div>
	{% endif %}
	<label for="id_phone" class="field-label"><em class="body-copy-alert">*</em> 
	{% trans 'Phone'%}</label>
	{{ form.phone }}
</div>
<div class="clear-left"></div>

<div class="field-wrapper">
	{% if form.email.errors %}
		<div class="errs">{{ form.email.errors }}</div>
	{% endif %}
	<label for="id_email" class="field-label"><em class="body-copy-alert">*</em> 
	{% trans 'Email'%}</label>
	{{ form.email }} 
</div>
<div class="clear-left"></div>

<div class="field-wrapper">
	{% if form.email_receipt.errors %}
		<div class="errs">{{ form.email_receipt.errors }}</div>
	{% endif %}
	<label for="id_email_receipt" class="field-label">{% trans 'Email Receipt?'%}</label>
	{{ form.email_receipt }} 
</div>
<div class="clear-left"></div>

<div class="section-header">
	Other Information
</div>

<div class="field-wrapper">
	{% if form.referral_source.errors %}
		<div class="errs">{{ form.referral_source.errors }}</div>
	{% endif %}
	<label for="id_referral_source" class="field-label">{% trans 'Referred by'%}</label>
	{{ form.referral_source }}
</div>
<div class="clear-left"></div>

<div class="field-wrapper">
	{% if form.comments.errors %}
		<div class="errs">{{ form.comments.errors }}</div>
	{% endif %}
	<label for="id_comments" class="field-label">{% trans 'Comments'%}</label>
	{{ form.comments }}
</div>
<div class="clear-left"></div>

<div class="submitbutton">
<input type="submit" name="submit" value="Submit" />
</div>
<div class="clear-right"></div>
</form>

</div>
</div>
{% endblock %}

plugins/donations/templates/donations/add_confirm.html
{% extends "donations/base.html" %}

{% block title %}Donation Confirmation{% endblock %}

{% block extra_head %}
{{ block.super }}
{% endblock %}

{% block body %}
<div class="t">

<h1>Donation Confirmation</h1>
<p>
Thank you for your donation!
</p>

</div>
{% endblock %}

plugins/donations/templates/donations/base.html
{% extends "site_base.html" %}

{% block title %}Donation{% endblock %}

{% block extra_body %}
{% endblock %}

plugins/donations/templates/donations/invoice_search_result_line.html
{% load base_filters %}
{% load invoice_tags %}

<table width="100%">
     {% invoices_search_line_header request invoice '#663300' %}  
       
     {# display donation info #} 
    
     <tr>
     	<td>DonationID</td>
     	<td>First Name</td>
     	<td>Last Name</td>
     	<td>Date</td>
     	<td>Amount</td>
     	<td>Balance</td>
     </tr>
     {% if obj %}
      <tr>
      	<td><a href="{% url donations.views.view obj.id %}">{{obj.id}}</a></td>
      	<td>{{obj.first_name}}</td>
      	<td>{{obj.last_name}}</td>
      	<td>{{obj.create_dt|date:'long'}}</td>
      	<td>{{obj.donation_amount|format_currency}}</td>
      	<td><div {% if invoice.balance > 0 %}class="body-copy-yellow"{% endif %}>{{invoice.balance|format_currency}}</div></td>
      </tr> 
      {% endif %}   
           
 </table>

plugins/donations/templates/donations/invoice_view_display.html
{% load base_filters %}

{# user info #}
<div class="invoice-view-box">
	{# make 3 blocks in the first box #}
	<div class="invoice-view-detail-left">
		{% if obj %}
			<a href="{% url donation.view  obj.id %}" title="View Donation Payment">{{  obj.id }}</a>
		{% else %}
			{{ invoice.object_id }}
		{% endif%}
	</div>
	
	<div class="invoice-view-detail-middle">
		<div class="invoice-item">
			{% if obj %}
				Donation contributed by {{  obj.first_name }} {{ obj.last_name}}
			{% else %}
				Donation Information not available
			{% endif%}
		</div>
		<div class="invoice-item">Phone: {{  obj.phone }}</div>
		<div class="invoice-item">Email: {{  obj.email }}</div>
		{% if  obj.company %}
			<div class="invoice-item">Company: {{  obj.company }}</div>
		{% endif%}
		{% if  obj.address or  obj.address2 or  obj.city or  obj.state or  obj.zip_code  %}
			<div class="invoice-item">Address: {{  obj.address }} {{  obj.address2 }}
				{{  obj.city }} {{  obj.state }} {{  obj.zip_code }}
			</div>
		{% endif%}
	</div>
	
	<div class="invoice-view-detail-right">
		Amount: {{ invoice.total|format_currency }}
	</div>
	<div class="clear-both"></div>
</div>

	

plugins/donations/templates/donations/nav.html
{% load base_tags %}
{% load perm_tags %}

{% has_perm user site_settings.change_setting as can_edit_setting %}

{% if nav_object %}
	{% has_perm user donations.view_donation nav_object as can_view_donation %}
{% else %}
	{% has_perm user donations.view_donation as can_view_donation %}
	{% has_perm user donations.change_donation as can_edit_donation %}
{% endif %}

<div id="showh">
	<ul id="primary">
	
    {% if user.is_authenticated %}
	<li>
	    <a href="{% url dashboard %}" title="Tendenci Home Page">
		<img border="0" src="{{ STATIC_URL }}images/tendenci34x15.gif"
		alt="Tendenci User Home" align="top" width="34" height="15"></a>
	</li>
    {% endif %}

	<li>
		<span>{% firstof MODULE_DONATIONS_LABEL 'Donations' %}</span>
		<ul id="secondary">
			<li><a href="{% url jobs %}">{% firstof MODULE_DONATIONS_LABEL 'Donations' %}:</a></li> 
			{% if can_edit_setting %}
				<li><a href="{% url settings.index "module" "donations" %}">Settings</a></li>
			{% endif %}
			{% if nav_object %}
				{% if can_view_donation %}
				<li><a href="{% url donation.view nav_object.id %}">View</a></li>
				{% endif %}
				
			{% endif %}
			<li><a href="{% url donation.search %}">Search</a></li>
			
			<li><a href="{% url donation.add %}">Add</a></li>
		
			{% if user.is_authenticated %}
			<li><a href="{% url auth_logout %}">Log Off</a></li> 
			{% endif %}
		</ul>
		
	</li>
	{% if MODULE_ARTICLES_ENABLED %}
	<li><a href="{% url articles %}">{% firstof MODULE_ARTICLES_LABEL 'Articles' %}</a></li>
	{% endif %}
	{% if MODULE_NEWS_ENABLED %}
	<li><a href="{% url news %}">{% firstof MODULE_NEWS_LABEL 'News' %}</a></li>
	{% endif %}
	</ul>
</div>

plugins/donations/templates/donations/payment_thankyou_display.html
<p>Thank you for your donation!</p>

plugins/donations/templates/donations/payment_thankyou_header.html
<h1>Donation Payment Status</h1>

plugins/donations/templates/donations/search-form.html
<form class="search-form" action="{% url donation.search %}" method="get">
<input type="text" name="q" value="{{ request.GET.q|striptags }}" />
<input type="submit" name="search" value="Search" />
</form>